package update

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// applyScript 是替换脚本的模板。@@PID@@ / @@ADDR@@ 会被替换掉。
//
// 为什么非要另起一个脚本：Windows 上正在运行的 exe 是锁着的，服务既删不掉
// 也覆盖不了自己。只能让服务先退出，再由外部进程动手。
//
// 两条硬性约束，都是踩过坑之后定下的：
//
//  1. 内容一律用 ASCII 英文。cmd.exe 按控制台的 OEM 代码页解释 .cmd，
//     这里写中文的话，换一台代码页不同的机器就可能变成乱码甚至语法错误。
//
//  2. **不许出现管道**（`a | b`）。这个脚本是被服务以"无控制台"方式拉起来的，
//     实测 `tasklist | find` 会卡死：find 迟迟等不到管道关闭，整个安装就停在
//     那里不动，用户看到的是"装完打不开了"。所以判断旧进程有没有退出这件事，
//     改成直接重试真正要做的那个操作——反正我们真正关心的只是"文件能不能换"，
//     "进程还在不在"本来也只是个代理指标。
const applyScript = `@echo off
rem Generated by CNC-Manager while installing an offline package.
rem Waits for the old server to release the exe, swaps in the new files,
rem then restarts. No pipelines in here on purpose -- see apply.go.
setlocal
cd /d "%~dp0.."
set "STAGE=%~dp0stage"
set "LOG=%~dp0apply-update.log"

echo [%DATE% %TIME%] install started, replacing pid @@PID@@ >> "%LOG%"

rem --- 1) replace the exe, retrying while the old server still holds it ---
rem The move is a rename on the same volume, so it is atomic. While the old
rem server is running this fails with "access denied"; once it exits the
rem first retry succeeds. Doing it first means that if we never get the file
rem back, nothing at all has been touched.
set /a WAITED=0
:retry_exe
move /y "%STAGE%\cnccool-server.exe" "cnccool-server.exe" >nul 2>&1
if not errorlevel 1 goto swap_web
set /a WAITED+=1
if %WAITED% GEQ 120 goto timeout
rem ping rather than timeout.exe: timeout refuses to run with redirected stdin
ping -n 2 127.0.0.1 >nul 2>&1
goto retry_exe

:timeout
echo [%DATE% %TIME%] FAILED: exe still locked after %WAITED% tries, nothing changed >> "%LOG%"
goto done

:swap_web
echo [%DATE% %TIME%] exe replaced after %WAITED% tries >> "%LOG%"

rem --- 2) replace the web folder ---
rem Renames again: fast, and the previous copy stays available as web.old
rem until we are sure the new one landed.
if exist "web.old" rd /s /q "web.old" >nul 2>&1
if not exist "web" goto move_new_web
move "web" "web.old" >nul 2>&1
if errorlevel 1 goto fail_move_old

:move_new_web
move "%STAGE%\web" "web" >nul 2>&1
if errorlevel 1 goto fail_move_new

if exist "%STAGE%\start.cmd" move /y "%STAGE%\start.cmd" "start.cmd" >nul 2>&1
if exist "%STAGE%\README.txt" move /y "%STAGE%\README.txt" "README.txt" >nul 2>&1
if exist "%STAGE%\VERSION" move /y "%STAGE%\VERSION" "VERSION" >nul 2>&1

rd /s /q "web.old" >nul 2>&1
rd /s /q "%STAGE%" >nul 2>&1
echo [%DATE% %TIME%] OK: files replaced >> "%LOG%"
goto restart

:fail_move_old
echo [%DATE% %TIME%] FAILED: could not move the old web folder aside, nothing changed >> "%LOG%"
goto done

:fail_move_new
rem The new exe is already in place at this point, so put the old web back:
rem old exe + new web would be a worse mix than new exe + old web.
if exist "web" rd /s /q "web" >nul 2>&1
if exist "web.old" move "web.old" "web" >nul 2>&1
echo [%DATE% %TIME%] FAILED: could not install the new web folder, old web restored >> "%LOG%"
goto restart

:restart
rem Relaunch the way a user would, but without popping a browser tab:
rem the tab that is already open reconnects by itself.
rem CNC_ADDR is passed through so a server started on a custom port
rem comes back on the same port.
set "CNC_NO_BROWSER=1"
set "CNC_ADDR=@@ADDR@@"
if not exist "start.cmd" goto restart_exe
start "" cmd /c start.cmd
goto done

:restart_exe
start "" cnccool-server.exe

:done
endlocal
`

// ApplyRequest 是生成替换脚本需要的全部信息。
type ApplyRequest struct {
	Layout Layout
	// PID 是当前服务的进程号。脚本会等这个进程退出，而不是等「叫 cnccool-server.exe
	// 的进程」——同一台机器上完全可能装着两份，按名字等会等错人。
	PID int
	// Addr 是服务当前监听的地址，重启时要沿用，否则换了端口用户就找不到了。
	Addr string
}

// WriteApplyScript 生成替换脚本，返回脚本路径。
func WriteApplyScript(req ApplyRequest) (string, error) {
	if err := os.MkdirAll(req.Layout.UpdateDir(), 0o755); err != nil {
		return "", fmt.Errorf("创建更新目录失败: %w", err)
	}

	script := strings.NewReplacer(
		"@@PID@@", strconv.Itoa(req.PID),
		"@@ADDR@@", req.Addr,
	).Replace(applyScript)

	// 行尾必须是 CRLF。cmd.exe 碰到只有 LF 的批处理，行为会变得很难预料。
	script = strings.ReplaceAll(script, "\r\n", "\n")
	script = strings.ReplaceAll(script, "\n", "\r\n")

	scriptPath := filepath.Join(req.Layout.UpdateDir(), applyScriptName)
	if err := os.WriteFile(scriptPath, []byte(script), 0o644); err != nil {
		return "", fmt.Errorf("写入替换脚本失败: %w", err)
	}
	return scriptPath, nil
}

// Flatten 把 root 里的内容挪到 stage 根目录下。
//
// 用户自己重新压过的包可能多套一层文件夹，而替换脚本是按固定路径找东西的，
// 所以在这里统一摊平，脚本那边就不用管包是怎么压出来的。
func Flatten(root, stage string) error {
	if root == stage {
		return nil
	}

	entries, err := os.ReadDir(root)
	if err != nil {
		return fmt.Errorf("读取解压结果失败: %w", err)
	}
	for _, e := range entries {
		from := filepath.Join(root, e.Name())
		to := filepath.Join(stage, e.Name())
		// root 就在 stage 下一层，同一卷，rename 是安全的
		if err := os.Rename(from, to); err != nil {
			return fmt.Errorf("整理解压结果失败: %w", err)
		}
	}
	return os.RemoveAll(root)
}
